name: Publish GitHub Pages
on:
  push:
    branches: [master]

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Pages
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Generate tag
        id: generate-tag
        run: echo "::set-output name=value::$(date '+%Y%m%d-%H%M%S')"
        env:
          TZ: Asia/Tokyo

      - name: Publish GitHub Pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/wktk/pdf-phs.git
          yarn deploy -- -g $TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.generate-tag.outputs.value }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.generate-tag.outputs.value }}
          release_name: Deployment @ ${{ steps.generate-tag.outputs.value }}
          body: Deployment @ ${{ steps.generate-tag.outputs.value }}
